Fix external-dns CrashLoopBackOff - remove conflicting flag
Removed --ignore-hostname-annotation flag which conflicts with annotation-based DNS management.
Error: 'FQDN Template must be set if ignoring annotations'

We explicitly want to use external-dns.alpha.kubernetes.io/hostname annotations,
so this flag should not be present.